# Generated by Django 2.1.5 on 2019-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('phone_number', models.DecimalField(decimal_places=10, max_digits=10)),
                ('second_phone_number', models.DecimalField(decimal_places=10, max_digits=10)),
                ('file', models.FileField(upload_to='photos/')),
            ],
        ),
    ]
